---
  dist: xenial
  language: python
  python:
    - "3.7"
  addons:
    apt:
      packages:
        - nginx
  install:
    - pip install ansible-lint
  script:
    - ansible-lint --version
    - ansible-lint *.yml
